name: Canary Build

on:
  repository_dispatch:
    types: [canary-build]
  workflow_dispatch:
    inputs:
      app-version:
        description: 'Application version to build (ex: canary-v2.1.4). Defaults to branch name. `canary-` prefix is added automatically'
        required: false
        type: string
        default: ''
      php-image-tag:
        description: 'PHP image version tag (ex: php-7.4.3-v1.0.0). Default to version in `ci/config.yaml`.'
        required: false
        type: string
        default: ''
      cache-routes:
        description: 'Cache routes (laravel). Default to `ci/config.yaml`.'
        required: false
        type: boolean
        default: false

jobs:
  canary-build:
    name: 'Canary Build'
    uses: adore-me/gha-workflows/.github/workflows/reusable-canary-build.yaml@v2.2.10
    with:
      app-version: ${{ github.event.inputs.app-version }}
      php-image-tag: ${{ github.event.inputs.php-image-tag }}
      cache-routes: ${{ github.event.inputs.cache-routes }}
    secrets:
      QUAY_USER: ${{ secrets.QUAY_USER }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
      GCR_CREDENTIALS: ${{ secrets.GCR_CREDENTIALS }}
      GH_PRIVATE_ACTIONS_TOKEN: ${{ secrets.GH_PRIVATE_ACTIONS_TOKEN_OLD_FORMAT }}