name: Canary Build Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  slash-command-dispatch:
    name: Canary Build Dispatch
    runs-on: ubuntu-latest
    steps:
      - name: Canary Dispatch
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.GH_PRIVATE_ACTIONS_TOKEN }}
          issue-type: pull-request
          event-type-suffix: -build
          dispatch-type: repository
          commands: |
            canary
