name: 'CI'
permissions: write-all
on:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    branches: [ main, master ]
    paths-ignore:
      - mkdocs.yml
      - catalog-info.yaml
      - README.md
      - local/**
      - ci/Jenkinsfile
      - ci/env.yml
      - ci/pipeline.yml
      - .github/workflows/**
env:
  APP_BUILD_CACHE_KEY: build-${{ github.event.repository.name }}-${{ github.sha }}
jobs:
  build-application:
    name: 'Build Application'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3.1.0

      - name: 'Login quay'
        uses: docker/login-action@v2.1.0
        with:
          registry: quay.io
          password: ${{ secrets.GHA_QUAY_ROBOT_PASSWORD }}
          username: ${{ secrets.GHA_QUAY_ROBOT_USERNAME }}

      - name: 'Set PHP image'
        id: set-php-image
        uses: adore-me/gha-image-setup@v1.1.2

      - name: 'Composer Install'
        uses: adore-me/gha-composer@v2.0.4
        with:
          gh-oauth-token: ${{ secrets.GH_PRIVATE_ACTIONS_TOKEN_OLD_FORMAT }}

      - name: 'Build cache (cache built code)'
        uses: actions/cache@v3.0.11
        with:
          key: ${{ env.APP_BUILD_CACHE_KEY }}
          path: ${{ github.workspace }}
  static-checks:
    needs: [ build-application ]
    name: 'Static Checks'
    runs-on: ubuntu-latest
    steps:
      - name: 'Login quay'
        uses: docker/login-action@v2.1.0
        with:
          registry: quay.io
          password: ${{ secrets.GHA_QUAY_ROBOT_PASSWORD }}
          username: ${{ secrets.GHA_QUAY_ROBOT_USERNAME }}

      - name: 'Build cache restore (get built code from build step)'
        uses: actions/cache@v3.0.11
        with:
          key: ${{ env.APP_BUILD_CACHE_KEY }}
          path: ${{ github.workspace }}

      - name: 'Set PHP image'
        id: set-php-image
        uses: adore-me/gha-image-setup@v1.1.2

      - name: 'Run Static Checks'
        id: static-checks
        uses: adore-me/gha-php-static-checks@v2.1.0
        with:
          run-phpcs: 'true'
          run-phpmd: 'true'
          run-phpcpd: 'true'
          run-phpstan: 'true'
  tests:
    needs: [ build-application ]
    name: 'Tests'
    runs-on: ubuntu-latest
    steps:
      - name: 'Login quay'
        uses: docker/login-action@v2.1.0
        with:
          registry: quay.io
          password: ${{ secrets.GHA_QUAY_ROBOT_PASSWORD }}
          username: ${{ secrets.GHA_QUAY_ROBOT_USERNAME }}

      - name: 'Build cache restore (get built code from build step)'
        uses: actions/cache@v3.0.11
        with:
          key: ${{ env.APP_BUILD_CACHE_KEY }}
          path: ${{ github.workspace }}

      - name: 'Set PHP image'
        id: set-php-image
        uses: adore-me/gha-image-setup@v1.1.2

      - name: 'Run PHPUnit'
        uses: adore-me/gha-phpunit@v2.3.3
        id: phpunit
        with:
          enable-mysql: true
          enable-redis: true
          with-coverage: true
          verbose: true
          run-suites: 'UnitTests'
  post-run-tasks:
    if: always()
    needs: [ build-application, static-checks, tests ]
    name: 'Post Run Tasks'
    runs-on: ubuntu-latest
    steps:
      - name: 'Upload artifacts to GCS'
        uses: adore-me/gha-gcs-upload-artifacts@v1.0.3
        with:
          gcs-bucket: gha-checks-artifacts
          gcs-sa: ${{ secrets.GCP_DEVOPS_SA }}

      - name: 'Cleanup cached build artifacts'
        if: always()
        uses: adore-me/gha-clean-cache@v1.0.2
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          key: ${{ env.APP_BUILD_CACHE_KEY }}
