name: 'Reusable CI workflow for front-end apps'

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
      CYPRESS_CURRENTS_RECORD_KEY:
        required: true

jobs:
  read-config:
    name: Read Config
    runs-on: ubuntu-latest
    outputs:
      nodeVersion: ${{ steps.config.outputs.nodeVersion }}
      runTests: ${{ steps.config.outputs.runTests }}
      cypressEnabled: ${{ steps.config.outputs.cypress-enabled }}
      cypressPort: ${{ steps.config.outputs.cypress-port }}
      cypressCurrentsLib: ${{ steps.config.outputs.cypress-currentsLib }}
      cypressFlags: ${{ steps.config.outputs.cypress-flags }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Read Config
        uses: actions-tools/yaml-outputs@v2
        id: config
        with:
          file-path: ci/config.yaml
          separator: '-'

      - name: Config Info
        run: |
          # Colors
          BL='\033[0;34m'
          NC='\033[0m'
          echo -e "${BL}Info:${NC} nodeVersion: ${{ steps.config.outputs.nodeVersion }}"
          echo -e "${BL}Info:${NC} runTests: ${{ steps.config.outputs.runTests }}"
          echo -e "${BL}Info:${NC} cypressEnabled: ${{ steps.config.outputs.cypress-enabled }}"
          echo -e "${BL}Info:${NC} cypressPort: ${{ steps.config.outputs.cypress-port }}"
          echo -e "${BL}Info:${NC} cypressCurrentsLib: ${{ steps.config.outputs.cypress-currentsLib }}"
          echo -e "${BL}Info:${NC} cypressFlags: ${{ steps.config.outputs.cypress-flags }}"
          echo -e "${BL}Info:${NC} installCommand: ${{ steps.config.outputs.installCommand }}"

  build-application:
    name: Build&Test Application
    needs:
      - read-config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
        with:
          persist-credentials: false

      - uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ needs.read-config.outputs.nodeVersion }}
          cache: npm

      - name: Authenticate with private NPM package
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          echo "unsafe-perm=true" >> .npmrc

      - name: NPM install
        id: npm-install
        run: |
          INSTALL_CMD="{{ steps.config.outputs.installCommand }}"
          if [[ -z "$INSTALL_CMD" ]]; then
            npm ci
          else
            npm ${{ steps.config.outputs.installCommand }}
          fi
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Provision app config
        id: provision-app-config
        run: |
          # Colors
          BL='\033[0;34m'
          if [[ -f ".env.template" ]]; then
            echo -e "${BL}Info:${NC} Using env .env.template"
          
            cp .env.template .env

            sed -i -e 's|{NAMESPACE}|ci|g' .env
            sed -i -e 's|{PROTOCOL}|http|g' .env
            sed -i -e 's|{ENV}|ci|g' .env
          else
            echo -e "${BL}Info:${NC} Using env ./src/env/env.dev.template"
          
            cp ./src/env/env.dev.template ./src/env/env.ts

            sed -i -e 's|APP_ENV|false|g' ./src/env/env.ts
            sed -i -e 's|NAMESPACE|ci|g' ./src/env/env.ts
          fi

      - name: NPM build
        id: npm-build
        run: npm run ci:build

      - name: NPM test
        if: ${{ needs.read-config.outputs.runTests == 'true' }}
        id: npm-test
        run: |
          npm run ci:test

# Need more work here. There are 2 frameworks for testing: jest and karma.
# We need some examples for both of them to go forward.
#      - name: Handle tests output
#        run: |
#          if [ "${{ steps.config.outputs.runTests }}" = "true" ]; then
#            echo "Tests output:"
#            cat ${{ steps.npm-test.outputs.testOutputPath }}
#          fi

  cypress-run:
    name: Cypress Tests
    needs:
     - read-config
    if: ${{ needs.read-config.outputs.cypressEnabled == 'true' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Setup xvfb (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get -y install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

      - name: Checkout
        uses: actions/checkout@v3.5.2
        with:
          persist-credentials: false

      - uses: actions/setup-node@v3.7.0
        with:
          node-version: ${{ needs.read-config.outputs.nodeVersion }}
          cache: npm

      - name: Provision app config
        id: provision-app-config
        run: |
          # Colors
          BL='\033[0;34m'
          if [[ -f ".env.template" ]]; then
            echo -e "${BL}Info:${NC} Using env .env.template"

            cp .env.template .env

            sed -i -e 's|{NAMESPACE}|ci|g' .env
            sed -i -e 's|{PROTOCOL}|http|g' .env
            sed -i -e 's|{ENV}|ci|g' .env
          else
            echo -e "${BL}Info:${NC} Using env ./src/env/env.dev.template"

            cp ./src/env/env.dev.template ./src/env/env.ts

            sed -i -e 's|APP_ENV|false|g' ./src/env/env.ts
            sed -i -e 's|NAMESPACE|ci|g' ./src/env/env.ts
          fi

      # Install NPM dependencies and run all Cypress tests
      - name: Cypress run
        id: cypress-run
        uses: cypress-io/github-action@v5.8.3
        with:
          install: true
          build: npm run ci:build
          start: npm run start
          wait-on: "http://127.0.0.1:${{ needs.read-config.outputs.cypressPort }}"
          wait-on-timeout: 120
          command: npx ${{ needs.read-config.outputs.cypressCurrentsLib }} ${{ needs.read-config.outputs.cypressFlags }} --key ${{ secrets.CYPRESS_CURRENTS_RECORD_KEY }} --ci-build-id ${{ github.repository }}-${{ github.run_id }}-${{ github.run_attempt}}
          ci-build-id: ${{ github.repository }}-${{ github.run_id }}-${{ github.run_attempt}}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_CURRENTS_RECORD_KEY }}
          DEBUG: '@cypress/github-action'

      - name: Upload screenshots
        uses: actions/upload-artifact@v3.1.2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: warn # 'warn' or 'error' are also available, defaults to `warn`

      - name: Results comment
        if: always()
        uses: actions/github-script@v6.4.1
        with:
          script: |
            const testResultsObject = '${{ steps.cypress-run.outputs.testResultsObject }}'
            if (testResultsObject == '') {
              console.log('No test results found')
              return
            }

            const testResults = JSON.parse(testResultsObject)
            const status = testResults.status ? '👋 Cypress tests OK!' : '🔥🔥🔥 Cypress tests failed 🔥🔥🔥'
            let summary = '<table>'
            sumary += '<tr><th>Result</th><th>Passed :white_check_mark:</th><th>Failed :x:</th><th>Pending :hand:</th><th>Skipped :leftwards_arrow_with_hook:</th><th>Duration :clock8:</th></tr>'
            summary += '<tr>'
            summary += '<td>' + (testResults.status ? 'Success :white_check_mark:' : 'Failing :red_circle:') + '</td>'
            summary += '<td>' + testResults.totalPassed + '</td>'
            summary += '<td>' + testResults.totalFailed + '</td>'
            summary += '<td>' + testResults.totalPending + '</td>'
            summary += '<td>' + testResults.totalSkipped + '</td>'
            summary += '<td>' + testResults.totalDuration + 's</td>'
            summary += '</tr>'
            summary += '</table>'
            const body = status + '\n' + summary

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })
