name: 'Static Checks reusable workflow for libs'

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
      QUAY_USER:
        required: true
      QUAY_PASSWORD:
        required: true
    inputs:
      php-image:
        description: 'PHP image to use'
        type: string
      run-phpcs:
        description: 'Run PHP Checkstyle'
        default: 'true'
        type: string
      phpcs-standard:
        description: 'PHP checkstyle standard to use, if run-phpcs is true'
        default: 'PSR2'
        type: string
      run-phpmd:
        description: 'Run PHP MD'
        default: 'true'
        type: string
      phpmd-app-dir:
        description: 'PHP MD application directory - add separate folders by using comma. When empty will try to guess if is `src` or `app`.'
        default: ''
        type: string
      run-phpcpd:
        description: 'Run PHP CPD'
        default: 'true'
        type: string
      run-phpstan:
        description: 'Run PHP Stan'
        default: 'true'
        type: string
      reports-dir:
        description: 'Reports base directory'
        default: 'build/reports'
        type: string
      app-dir:
        description: 'Application directory - use without trailing slash. When empty will try to guess if is `src` or `app`.'
        default: ''
        type: string
      run-rector:
        description: 'Run PHP Rector'
        default: 'false'
        type: string
      run-laravel-pint:
        description: 'Run Laravel Pint'
        default: 'false'
        type: string
      github-token:
        description: 'Github token'
        default: ''
        type: string

permissions: write-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Add config.yaml'
        run: |
          if [ -f ci/config.yaml ]; then
            exit 0
          else 
            mkdir ci
            touch ci/config.yaml
            echo "image-tag: php-7.1.33-v1.0.0" > ci/config.yaml
          fi

      - name: 'Set PHP image'
        uses: adore-me/gha-image-setup@v1.1.5

      - name: 'Login quay'
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: 'Validate composer.json and composer.lock'
        run: composer validate --strict

      - name: 'Composer Install'
        uses: adore-me/gha-composer@v2.1.3
        with:
          cache: true
          gh-oauth-token: ${{ secrets.GH_PRIVATE_ACTIONS_TOKEN_OLD_FORMAT }}

      - name: 'Run Static Checks'
        uses: adore-me/gha-php-static-checks@v2.1.17
        with:
          app-dir: ${{ inputs.app-dir }}
          github-token: ${{ secrets.GH_TOKEN }}
          phpmd-app-dir: ${{ inputs.phpmd-app-dir }}
          run-phpcpd: ${{ inputs.run-phpcpd }}
          run-phpcs: ${{ inputs.run-phpcs }}
          run-phpmd: ${{ inputs.run-phpmd }}
          run-phpstan: ${{ inputs.run-phpstan }}
          run-rector: ${{ inputs.run-rector }}
          run-laravel-pint: ${{ inputs.run-laravel-pint }}
