name: 'Static Checks reusable workflow for libs'

on:
  workflow_call:
    secrets:
      GH_KEY:
        required: true
      QUAY_USER:
        required: true
      QUAY_PASSWORD:
        required: true
      APP_ID:
        required: true
    inputs:
      php-image:
        description: 'PHP image to use'
        type: string
      run-phpcs:
        description: 'Run PHP Checkstyle'
        default: 'true'
        type: string
      phpcs-standard:
        description: 'PHP checkstyle standard to use, if run-phpcs is true'
        default: 'PSR2'
        type: string
      run-phpmd:
        description: 'Run PHP MD'
        default: 'true'
        type: string
      phpmd-app-dir:
        description: 'PHP MD application directory - add separate folders by using comma. When empty will try to guess if is `src` or `app`.'
        default: ''
        type: string
      run-phpcpd:
        description: 'Run PHP CPD'
        default: 'true'
        type: string
      run-phpstan:
        description: 'Run PHP Stan'
        default: 'true'
        type: string
      reports-dir:
        description: 'Reports base directory'
        default: 'build/reports'
        type: string
      app-dir:
        description: 'Application directory - use without trailing slash. When empty will try to guess if is `src` or `app`.'
        default: ''
        type: string
      run-rector:
        description: 'Run PHP Rector'
        default: 'false'
        type: string
      run-laravel-pint:
        description: 'Run Laravel Pint'
        default: 'false'
        type: string
      github-token:
        description: 'Github token'
        default: ''
        type: string

permissions:
  actions: read
  contents: read
  checks: read

jobs:
  static-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: 'Create token'
        id: gha-token
        uses: actions/create-github-app-token@v1.9.0
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.GH_KEY }}
          owner: ${{ github.repository_owner }}

      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: 'Login quay'
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: 'Set PHP image'
        uses: adore-me/gha-image-setup@v1.1.5

      - name: 'Composer Install'
        uses: adore-me/gha-composer@v3.0.4
        with:
          check-lock: false
          run-install: true
          composer-self-update: true
          gh-oauth-token: ${{ steps.gha-token.outputs.token }}

      - name: 'Run Static Checks'
        uses: adore-me/gha-php-static-checks@v2.1.17
        with:
          app-dir: ${{ inputs.app-dir }}
          github-token: ${{ steps.gha-token.outputs.token }}
          phpmd-app-dir: ${{ inputs.phpmd-app-dir }}
          phpcs-standard: ${{ inputs.phpcs-standard }}
          run-phpcpd: ${{ inputs.run-phpcpd }}
          run-phpcs: ${{ inputs.run-phpcs }}
          run-phpmd: ${{ inputs.run-phpmd }}
          run-phpstan: ${{ inputs.run-phpstan }}
          run-rector: ${{ inputs.run-rector }}
          run-laravel-pint: ${{ inputs.run-laravel-pint }}
          reports-dir: ${{ inputs.reports-dir }}
