name: 'Reusable continuous deployment workflow'

on:
  workflow_call:
    inputs:
      prod-gcp-project-id:
        description: 'GCP project ID for production'
        required: true
        type: string
      create-jira-tickets:
        description: 'Create jira tickets and link items based on commit history'
        default: true
        required: false
        type: boolean
      php-image-name:
        description: 'PHP image name (ex: nginx-fpm-alpine)'
        required: false
        type: string
        default: 'nginx-fpm-alpine'
      composer-self-update:
        description: 'Run composer self-update'
        required: false
        type: boolean
        default: false
      composer-self-update-version:
        description: 'Composer self-update version'
        required: false
        type: string
        default: ''
      slack-channel:
        description: 'Slack channel for error notifications'
        required: true
        type: string
        default: ''
    secrets:
      QUAY_USER:
        required: true
      QUAY_PASSWORD:
        required: true
      GCR_CREDENTIALS:
        required: true
      JIRA_USER:
        required: true
      JIRA_PASSWORD:
        required: true
      JIRA_URI:
        required: true
      SLACK_WEBHOOK:
        required: true

jobs:
  release:
    name: 'Release new version'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        id: checkout
        uses: actions/checkout@v4.1.1

      - name: 'Remove tests folder'
        run:
          if [ -d tests ]; then 
            rm -rf tests; 
            echo "Tests folder removed";
          else
            echo "No tests folder to remove";
          fi

      - name: 'Create release'
        id: release
        uses: rymndhng/release-on-push-action@v0.28.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          use_github_release_notes: true
          bump_version_scheme: patch
          tag_prefix: v

      - name: 'Login Docker registry (Quay)'
        id: login-quay
        uses: docker/login-action@v3.0.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }} # Use org secrets for this
          password: ${{ secrets.QUAY_PASSWORD }} # Use org secrets for this

      - name: 'Login backup Docker registry (GCR)'
        id: login-backup-gcr
        uses: docker/login-action@v3.0.0
        with:
          registry: us.gcr.io
          username: _json_key
          password: ${{ secrets.GCR_CREDENTIALS }} # Use org secrets for this

      - name: 'Set PHP image'
        id: set-php-image
        uses: adore-me/gha-image-setup@v1.1.6
        with:
          name: ${{ inputs.php-image-name }}

      - name: 'Composer Install'
        id: composer-install
        uses: adore-me/gha-composer@v2.1.3
        with:
          composer-self-update: ${{ inputs.composer-self-update }}
          composer-self-update-version: ${{ inputs.composer-self-update-version }}
          composer-no-dev: 'true'
          cache: 'true'
          gh-oauth-token: ${{ secrets.GH_OAUTH_TOKEN }}

      - name: 'Get route cache option from CI config'
        id: project-cache-routes
        uses: adore-me/read-yaml@v1.0.0
        with:
          file: './ci/config.yaml'
          key-path: '["prod-cache-routes"]'

      - name: 'Running extra commands'
        id: run-extra-commands
        uses: adore-me/gha-run-cmds@v1.1.5
        with:
          run-laravel-route-cache: ${{ steps.project-cache-routes.outputs.data }}

      - name: 'Docker build & push image'
        id: docker-build-push
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: ci/Dockerfile
          push: true
          labels: |
            app.version=${{ steps.release.outputs.tag_name }}
            app.cache.routes=${{ steps.project-cache-routes.outputs.data }}
            git.commit.sha=${{ github.sha }}
            php.image.tag=${{ steps.set-php-image.outputs.project-image-tag }}
            image.type=production
          tags: |
            quay.io/adoreme/${{ github.event.repository.name }}:${{ steps.release.outputs.tag_name }}
            us.gcr.io/${{ inputs.prod-gcp-project-id }}/${{ github.event.repository.name }}:${{ steps.release.outputs.tag_name }}

      - name: Send data to Slack workflow
        uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          config: .github/workflows/config/slack.yaml
          channel: ${{ inputs.slack-channel }}
          steps: ${{ toJson(steps) }}
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
    outputs:
      tag: ${{ steps.release.outputs.tag_name }}

  create-jira-ticket:
    name: 'Create JIRA ticket'
    needs: [ release ]
    runs-on: ubuntu-latest
    steps:
      - name: 'Find out if the update is made from a pull request; get the PR number'
        uses: actions/github-script@v6.4.1
        if: inputs.create-jira-tickets
        id: pr-id
        with:
          result-encoding: string
          script: |
            const msg = (context.payload.head_commit.message).match(/#\d+/);
            let pr= Array.isArray(msg) ? parseInt(msg[0].replace('#','')) : 0
            console.log("this is pr number: " + pr)
            return pr

      - name: 'Create jira tickets and link items, send deployment notification'
        uses: adore-me/github-action-deploysbot@v1.0.2
        if: inputs.create-jira-tickets && steps.pr-id.outputs.result > 0
        with:
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}
          JIRA_URI: ${{ secrets.JIRA_URI }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PR_NUMBER: ${{ steps.pr-id.outputs.result }}
          GH_TAG: ${{ needs.release.outputs.tag }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
