name: 'Reusable continuous deployment workflow (promote to prod)'

on:
  workflow_call:
    inputs:
      backup:
        description: 'Push image to backup registry'
        default: true
        required: false
        type: boolean
      prod-gcp-project-id:
        description: 'GCP project ID for production'
        required: true
        type: string
    secrets:
      QUAY_USER:
        required: true
      QUAY_PASSWORD:
        required: true
      GCR_CREDENTIALS:
        required: true

jobs:
  prepare-tags:
    name: 'Setup tags'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Output tags'
        id: tags
        run: |
          TAG=$(git describe --abbrev=0)
          IMAGE="quay.io/adoreme/${{ github.event.repository.name }}"
          IMAGE_BACKUP="us.gcr.io/${{ inputs.prod-gcp-project-id }}/${{ github.event.repository.name }}"
          echo ::set-output name=tag::${TAG}
          echo ::set-output name=rc-tag::${IMAGE}:rc-${TAG}
          echo ::set-output name=prod-tag::${IMAGE}:prod-${TAG}
          echo ::set-output name=prod-tag-backup::${IMAGE_BACKUP}:prod-${TAG}

    outputs:
      tag: ${{ steps.tags.outputs.tag }}
      rc-tag: ${{ steps.tags.outputs.rc-tag }}
      prod-tag: ${{ steps.tags.outputs.prod-tag }}
      prod-tag-backup: ${{ steps.tags.outputs.prod-tag-backup }}

  push-main-image:
    name: 'Tag/Push prod image (Quay)'
    needs: [prepare-tags]
    runs-on: ubuntu-latest
    steps:
      - name: 'Login Docker registry (Quay)'
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }} # Use org secrets for this
          password: ${{ secrets.QUAY_PASSWORD }} # Use org secrets for this

      - name: 'Pull rc Docker image'
        run: docker pull ${{ needs.prepare-tags.outputs.rc-tag }}

      - name: 'Tag prod Docker image'
        run: docker tag ${{ needs.prepare-tags.outputs.rc-tag }} ${{ needs.prepare-tags.outputs.prod-tag }}

      - name: 'Push prod Docker image'
        run: docker push ${{ needs.prepare-tags.outputs.prod-tag }}

  push-backup-image:
    name: 'Tag/Push backup image (GCR)'
    needs: [prepare-tags]
    if: ${{ inputs.backup }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Login Docker registry (Quay)'
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }} # Use org secrets for this
          password: ${{ secrets.QUAY_PASSWORD }} # Use org secrets for this

      - name: 'Pull rc Docker image'
        run: docker pull ${{ needs.prepare-tags.outputs.rc-tag }}

      - name: 'Login backup Docker registry (GCR)'
        uses: docker/login-action@v1
        with:
          registry: us.gcr.io
          username: _json_key
          password: ${{ secrets.GCR_CREDENTIALS }}

      - name: 'Tag prod backup Docker image'
        run: docker tag ${{ needs.prepare-tags.outputs.rc-tag }} ${{ needs.prepare-tags.outputs.prod-tag-backup }}

      - name: 'Push prod Docker image to backup registry'
        run: docker push ${{ needs.prepare-tags.outputs.prod-tag-backup }}

  create-release:
    name: 'Create release'
    needs: [prepare-tags, push-main-image]
    runs-on: ubuntu-latest
    steps:
    - name: 'Create release'
      uses: ncipollo/release-action@v1.9.0
      with:
        tag: ${{ needs.prepare-tags.outputs.tag }}
        name: v${{ needs.prepare-tags.outputs.tag }}
        body: "Released `v${{ needs.prepare-tags.outputs.tag }}` with image tag `prod-${{ needs.prepare-tags.outputs.tag }}`"
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
