name: Cleanup Build Cache
on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  cleanup-cache:
    name: Cleanup cached build artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deleting cache related to PR
        run: |
          sudo apt-get -q update
          sudo apt-get -q install -y jq
          
          # Get complete cache list
          cache_list=$(curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/adore-me/ms-tap/actions/caches | jq -r '.actions_caches[].key')
          echo -e "Cache list:\n$cache_list"
          echo ""
          
          # Get complete cache list related to PR
          cache_list_pr=$(echo "$cache_list" | grep "${{github.event.number}}")
          if [[ -n $cache_list_pr ]]; then
            echo -e "Cache list related to pr:\n$cache_list_pr"
            echo ""
          else
            echo "Cache list related to PR is empty"
            exit 0
          fi
          
          # Cleanup build cached related to pr
          if [[ -n "$cache_list_pr" ]]; then
            echo "$cache_list_pr" | while IFS= read -r line; do
              cleaned_line=$(echo "$line" | xargs)
              echo "Deleting cache: $cleaned_line"
              curl -L \
              -X DELETE \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/adore-me/ms-tap/actions/caches?key=$cleaned_line"
            done
          else
            echo "No cache found related to pr"
            exit 0
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
