name: Reusable promote to PROD workflow

on: 
  workflow_call:
    inputs: 
      version:
        description: 'Version to promote (ex: v1.0.3)'
        type: string
        required: true
    secrets:
      GH_OAUTH_TOKEN:
        required: true
      QUAY_USER:
        required: true
      QUAY_PASSWORD:
        required: true
      GCR_CREDENTIALS:
        required: true
jobs:
  promote:
    name: Promote to PROD
    runs-on: ubuntu-latest
    steps: 
      - name: Login Docker registry (Quay)
        uses: docker/login-action@v2.1.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }} # Use org secrets for this
          password: ${{ secrets.QUAY_PASSWORD }} # Use org secrets for this
      - name: Login backup Docker registry (GCR)
        uses: docker/login-action@v2.1.0
        with:
          registry: us.gcr.io
          username: _json_key
          password: ${{ secrets.GCR_CREDENTIALS }} # Use org secrets for this
      - name: Setup ENV
        run: |-
          UAT_IMAGE_TAG=quay.io/adoreme/${{github.repository.name}}:${{ github.event.inputs.version }}
          QUAY_PROD_IMAGE_TAG=quay.io/adoreme/${{github.repository.name}}:prod-${{ github.event.inputs.version }}
          GCR_PROD_IMAGE_TAG=us.gcr.io/am-production-268015/${{github.repository.name}}:prod-${{ github.event.inputs.version }}
      - name: Pull image from Quay
        run: docker pull $UAT_IMAGE_TAG
      - name: Tag image for Quay and Push
        run: |-
          docker tag $UAT_IMAGE_TAG $QUAY_PROD_IMAGE_TAG
          docker push $QUAY_PROD_IMAGE_TAG
      - name: Tag image for GCR and Push
        run: |-
          docker tag $UAT_IMAGE_TAG $GCR_PROD_IMAGE_TAG
          docker push $GCR_PROD_IMAGE_TAG
      - name: Update release
        uses: irongut/EditRelease@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          id: ${{ github.event.release.id }}
          name: "prod-${{ github.event.inputs.version }}"
          replacename: true
      - name: 'Summarize with Docker image Success'
        run: |
          echo 'Version `${{ github.event.inputs.version }}` promoted to PROD as `prod-${{ github.event.inputs.version }}`' >> $GITHUB_STEP_SUMMARY
