name: 'Reusable continuous deployment workflow (promote to prod)'

on:
  workflow_call:
    inputs:
      backup:
        description: 'Push image to backup registry'
        default: true
        required: false
        type: boolean
      prod-gcp-project-id:
        description: 'GCP project ID for production'
        required: true
        type: string
      create-jira-tickets:
        description: 'Create jira tickets and link items based on commit history'
        default: true
        required: false
        type: boolean
    secrets:
      QUAY_USER:
        required: true
      QUAY_PASSWORD:
        required: true
      GCR_CREDENTIALS:
        required: true
      JIRA_USER:
        required: true
      JIRA_PASSWORD:
        required: true
      JIRA_URI:
        required: true
      SLACK_WEBHOOK:
        required: true
      DEPLOYS_BOT_HEADER:
        required: true
      DEPLOYS_BOT_HEADER_VALUE:
        required: true

jobs:
  setup-tags:
    name: 'Setup tags'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Output tags'
        id: tags
        run: |
          TAG=$(git describe --abbrev=0)
          IMAGE="quay.io/adoreme/${{ github.event.repository.name }}"
          IMAGE_BACKUP="us.gcr.io/${{ inputs.prod-gcp-project-id }}/${{ github.event.repository.name }}"
          echo ::set-output name=tag::${TAG}
          echo ::set-output name=rc-tag::${IMAGE}:rc-${TAG}
          echo ::set-output name=prod-tag::${IMAGE}:prod-${TAG}
          echo ::set-output name=prod-tag-backup::${IMAGE_BACKUP}:prod-${TAG}

    outputs:
      tag: ${{ steps.tags.outputs.tag }}
      rc-tag: ${{ steps.tags.outputs.rc-tag }}
      prod-tag: ${{ steps.tags.outputs.prod-tag }}
      prod-tag-backup: ${{ steps.tags.outputs.prod-tag-backup }}

  push-main-image:
    name: 'Tag/Push prod image (Quay)'
    needs: [setup-tags]
    runs-on: ubuntu-latest
    steps:
      - name: 'Login Docker registry (Quay)'
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }} # Use org secrets for this
          password: ${{ secrets.QUAY_PASSWORD }} # Use org secrets for this

      - name: 'Pull rc Docker image'
        run: docker pull ${{ needs.setup-tags.outputs.rc-tag }}

      - name: 'Tag prod Docker image'
        run: docker tag ${{ needs.setup-tags.outputs.rc-tag }} ${{ needs.setup-tags.outputs.prod-tag }}

      - name: 'Push prod Docker image'
        run: docker push ${{ needs.setup-tags.outputs.prod-tag }}

  push-backup-image:
    name: 'Tag/Push backup image (GCR)'
    needs: [setup-tags]
    if: ${{ inputs.backup }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Login Docker registry (Quay)'
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }} # Use org secrets for this
          password: ${{ secrets.QUAY_PASSWORD }} # Use org secrets for this

      - name: 'Pull rc Docker image'
        run: docker pull ${{ needs.setup-tags.outputs.rc-tag }}

      - name: 'Login backup Docker registry (GCR)'
        uses: docker/login-action@v1
        with:
          registry: us.gcr.io
          username: _json_key
          password: ${{ secrets.GCR_CREDENTIALS }}

      - name: 'Tag prod backup Docker image'
        run: docker tag ${{ needs.setup-tags.outputs.rc-tag }} ${{ needs.setup-tags.outputs.prod-tag-backup }}

      - name: 'Push prod Docker image to backup registry'
        run: docker push ${{ needs.setup-tags.outputs.prod-tag-backup }}

  create-release:
    name: 'Create release'
    needs: [setup-tags, push-main-image]
    runs-on: ubuntu-latest
    steps:
    - name: 'Create release'
      uses: ncipollo/release-action@v1.9.0
      with:
        tag: ${{ needs.setup-tags.outputs.tag }}
        name: v${{ needs.setup-tags.outputs.tag }}
        body: "Released `v${{ needs.setup-tags.outputs.tag }}` with image tag `prod-${{ needs.setup-tags.outputs.tag }}`"
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
    - name: "Find out if the update is made from a pull request; get the PR number"
      uses: actions/github-script@v5
      if: ${{ inputs.create-jira-tickets }}
      id: pr_id
      with:
        result-encoding: string
        script: |
          const msg = (context.payload.head_commit.message).match(/#\d+/);
          let pr= Array.isArray(msg) ? parseInt(msg[0].replace('#','')) : 0
          console.log("this is pr number: " + pr)
          return pr
    - name: "Create jira tickets and link items, send deployment notification"
      uses: adore-me/github-action-deploysbot@master
      if: "${{ inputs.create-jira-tickets && steps.pr_id.outputs.result > 0}}"
      with:
        JIRA_USER: ${{ secrets.JIRA_USER }}
        JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}
        JIRA_URI: ${{ secrets.JIRA_URI }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_PR_NUMBER: ${{ steps.pr_id.outputs.result }}
        GH_TAG: ${{ needs.setup-tags.outputs.prod-tag }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        DEPLOYS_BOT_HEADER: ${{ secrets.DEPLOYSBOT_HEADER }}
        DEPLOYS_BOT_HEADER_VALUE: ${{ secrets.DEPLOYSBOT_HEADER_VALUE }}
