name: Reusable Cleanup Build Cache
on:
  workflow_call:
    secrets:
      GITHUB_API_TOKEN:
        required: true

jobs:
  cleanup-cache:
    name: Cleanup cached build artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Create token
        id: gha-token
        uses: actions/create-github-app-token@v1.9.0
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.GH_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Deleting cache related to PR
        id: cleanup-cache
        run: |
          # Get complete cache list
          cache_list=$(curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ steps.gha-token.outputs.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/adore-me/${{ github.event.repository.name }}/actions/caches | jq -r '.actions_caches[].key')
          echo -e "Cache list:\n$cache_list"
          echo ""
          if [[ -z $cache_list ]]; then
            echo "::warning::No cache found"
            exit 0
          fi
          
          # Get complete cache list related to PR
          cache_list_pr=$(echo "$cache_list" | grep -e "-${{github.event.number}}-"), echo "$?"
          if [[ -n $cache_list_pr ]]; then
            echo -e "Cache list related to pr:\n$cache_list_pr"
            echo ""
          else
            echo "Cache list related to PR is empty"
            exit 0
          fi
          
          # Cleanup build cached related to pr
          if [[ -n "$cache_list_pr" ]]; then
            echo "$cache_list_pr" | while IFS= read -r line; do
              cleaned_line=$(echo "$line" | xargs)
              echo "Deleting cache: $cleaned_line"
              curl -L \
              -X DELETE \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${{ steps.gha-token.outputs.token }}" \
              "https://api.github.com/repos/adore-me/${{ github.event.repository.name }}/actions/caches?key=$cleaned_line"
            done
          else
            echo "No cache found related to pr"
            exit 0
          fi
