name: 'Sync app env to kube dev (reusable)'

on:
  workflow_call:
    inputs:
      enable:
        description: 'Enable the workflow'
        default: true
        required: false
        type: boolean
    secrets:
      GH_KEY:
        required: true
      APP_ID:
        required: true

jobs:
  sync-env:
    name: 'Sync app env to kube-dev'
    if: ${{ inputs.enable }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
      - name: Create token
        id: gha-token
        uses: actions/create-github-app-token@v1.9.0
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.GH_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Copy and push the env file to kube-dev
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ steps.gha-token.outputs.token }}
        with:
          source_file: "ci/env.yml"
          destination_repo: 'adore-me/kube-dev'
          destination_folder: "resources/base/apps/${{ github.event.repository.name }}/"
          user_email: 'ops+jenkins@adoreme.com'
          user_name: 'AdoreMeJenkins'
          commit_message: 'Update ${{ github.event.repository.name }}-env'
          destination_branch: 'master'
